[package]
name = "aggregate-map"
version = "1.0.0"
edition = "2021"


[features]
default = ["hashmap"]
hashmap = []
btreemap = []
serde = ["dep:serde"]

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }
